### ISSUE TITLE
Not possible to search by query

### ISSUE THREAD

**Issue by andtsarenko** [ewnd9/opensubtitles-universal-api#1]
> openSubtitles.search({
>     query: 'How I meet your mother'
> }).then((data) => {
>     console.info(data);
> });

fails with error:
**Uncaught TypeError: Cannot read property 'replace' of undefined**
at line:

>  var imdbId = query.imdbid.replace('tt', '');

**Comment by ewnd9** [comment]
Closed by https://github.com/ewnd9/opensubtitles-universal-api/commit/40edf736e078a82d8529f5cb4c2d5f5ba0612390 Additional discussion happened in https://github.com/ewnd9/opensubtitles-universal-api/pull/2
